name: MoshiOnlineDesktop

# Controls when the action will run. 
on:
  # Triggers the workflow on push for production branch
  push:
    branches: 
       - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build MoshiOnlineDesktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10' 
        
      - name: Setup MSBuild
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install dependencies
        run: yarn
      
      - name: Make and Publish (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}

      - name: Make and Publish (WINDOWS)
        if: startsWith(matrix.os, 'windows')
        run: yarn run publish-windows
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
        
      - name: Make and Publish (MAC)
        if: startsWith(matrix.os, 'macos')
        run: yarn run publish-mac
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
