name: Build & Release Electron App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Generate Version Tag
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: version
        run: |
          VERSION=$(jq -r ".version" package.json)
          TAG="v$VERSION"
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Create release tag
        run: |
          git tag ${{ steps.version.outputs.version }} || echo "Tag already exists"
          git push origin ${{ steps.version.outputs.version }} || echo "Tag exists, skipping"

      - name: Create GitHub Release (empty)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          name: "Release ${{ steps.version.outputs.version }}"
          draft: false
          prerelease: false
          allowUpdates: true


  build:
    name: Build Release Artifacts
    needs: tag
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Setup MSBuild (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        run: npm ci --force

      - name: Build (electron forge)
        run: npm run make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-artifacts"
          path: out/**/*

  upload:
    name: Upload Files to GitHub Release
    needs: [tag, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files

      - name: Upload assets to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.version }}
          artifacts: "release_files/**"
          allowUpdates: true
          draft: false
